### ISSUE TITLE
tag_1.Tag is not a constructor

### ISSUE THREAD

**Issue by moussa2100** [axenda/zatca#6]
invoice.js:14 
        
       Uncaught (in promise) TypeError: tag_1.Tag is not a constructor
    at new Invoice (invoice.js:14:13)
    at _callee$ (App.jsx:32:25)
    at tryCatch (regeneratorRuntime.js:86:17)
    at Generator.eval [as _invoke] (regeneratorRuntime.js:66:24)
    at Generator.eval [as next] (regeneratorRuntime.js:117:21)

**Comment by ihadabs** [comment]
Hey @moussa2100,
It's not clear where the issue is, can you provide some code that produces the issue.
